services:
  pg:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  odoo:
    build: .
    platform: linux/amd64
    ports:
      - "8071:8069"
    depends_on:
      pg:
        condition: service_healthy
    environment:
      HOST: pg
      USER: odoo
      PASSWORD: odoo
    command:
      - odoo
      - -i base
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
volumes:
  pgdata:
  odoo_data:
